/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WelcomeIndexRouteImport } from './routes/welcome/index'
import { Route as VaultVaultIdRouteImport } from './routes/vault/$vaultId'
import { Route as VaultVaultIdIndexRouteImport } from './routes/vault/$vaultId/index'
import { Route as ChatPopupThreadIdIndexRouteImport } from './routes/chat-popup/$threadId/index'
import { Route as VaultVaultIdSettingsRouteImport } from './routes/vault/$vaultId/settings'
import { Route as VaultVaultIdThreadThreadIdRouteImport } from './routes/vault/$vaultId/thread/$threadId'

const WelcomeIndexRoute = WelcomeIndexRouteImport.update({
  id: '/welcome/',
  path: '/welcome/',
  getParentRoute: () => rootRouteImport,
} as any)
const VaultVaultIdRoute = VaultVaultIdRouteImport.update({
  id: '/vault/$vaultId',
  path: '/vault/$vaultId',
  getParentRoute: () => rootRouteImport,
} as any)
const VaultVaultIdIndexRoute = VaultVaultIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => VaultVaultIdRoute,
} as any)
const ChatPopupThreadIdIndexRoute = ChatPopupThreadIdIndexRouteImport.update({
  id: '/chat-popup/$threadId/',
  path: '/chat-popup/$threadId/',
  getParentRoute: () => rootRouteImport,
} as any)
const VaultVaultIdSettingsRoute = VaultVaultIdSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => VaultVaultIdRoute,
} as any)
const VaultVaultIdThreadThreadIdRoute =
  VaultVaultIdThreadThreadIdRouteImport.update({
    id: '/thread/$threadId',
    path: '/thread/$threadId',
    getParentRoute: () => VaultVaultIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/vault/$vaultId': typeof VaultVaultIdRouteWithChildren
  '/welcome/': typeof WelcomeIndexRoute
  '/vault/$vaultId/settings': typeof VaultVaultIdSettingsRoute
  '/chat-popup/$threadId/': typeof ChatPopupThreadIdIndexRoute
  '/vault/$vaultId/': typeof VaultVaultIdIndexRoute
  '/vault/$vaultId/thread/$threadId': typeof VaultVaultIdThreadThreadIdRoute
}
export interface FileRoutesByTo {
  '/welcome': typeof WelcomeIndexRoute
  '/vault/$vaultId/settings': typeof VaultVaultIdSettingsRoute
  '/chat-popup/$threadId': typeof ChatPopupThreadIdIndexRoute
  '/vault/$vaultId': typeof VaultVaultIdIndexRoute
  '/vault/$vaultId/thread/$threadId': typeof VaultVaultIdThreadThreadIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/vault/$vaultId': typeof VaultVaultIdRouteWithChildren
  '/welcome/': typeof WelcomeIndexRoute
  '/vault/$vaultId/settings': typeof VaultVaultIdSettingsRoute
  '/chat-popup/$threadId/': typeof ChatPopupThreadIdIndexRoute
  '/vault/$vaultId/': typeof VaultVaultIdIndexRoute
  '/vault/$vaultId/thread/$threadId': typeof VaultVaultIdThreadThreadIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/vault/$vaultId'
    | '/welcome/'
    | '/vault/$vaultId/settings'
    | '/chat-popup/$threadId/'
    | '/vault/$vaultId/'
    | '/vault/$vaultId/thread/$threadId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/welcome'
    | '/vault/$vaultId/settings'
    | '/chat-popup/$threadId'
    | '/vault/$vaultId'
    | '/vault/$vaultId/thread/$threadId'
  id:
    | '__root__'
    | '/vault/$vaultId'
    | '/welcome/'
    | '/vault/$vaultId/settings'
    | '/chat-popup/$threadId/'
    | '/vault/$vaultId/'
    | '/vault/$vaultId/thread/$threadId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  VaultVaultIdRoute: typeof VaultVaultIdRouteWithChildren
  WelcomeIndexRoute: typeof WelcomeIndexRoute
  ChatPopupThreadIdIndexRoute: typeof ChatPopupThreadIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/welcome/': {
      id: '/welcome/'
      path: '/welcome'
      fullPath: '/welcome/'
      preLoaderRoute: typeof WelcomeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vault/$vaultId': {
      id: '/vault/$vaultId'
      path: '/vault/$vaultId'
      fullPath: '/vault/$vaultId'
      preLoaderRoute: typeof VaultVaultIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vault/$vaultId/': {
      id: '/vault/$vaultId/'
      path: '/'
      fullPath: '/vault/$vaultId/'
      preLoaderRoute: typeof VaultVaultIdIndexRouteImport
      parentRoute: typeof VaultVaultIdRoute
    }
    '/chat-popup/$threadId/': {
      id: '/chat-popup/$threadId/'
      path: '/chat-popup/$threadId'
      fullPath: '/chat-popup/$threadId/'
      preLoaderRoute: typeof ChatPopupThreadIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vault/$vaultId/settings': {
      id: '/vault/$vaultId/settings'
      path: '/settings'
      fullPath: '/vault/$vaultId/settings'
      preLoaderRoute: typeof VaultVaultIdSettingsRouteImport
      parentRoute: typeof VaultVaultIdRoute
    }
    '/vault/$vaultId/thread/$threadId': {
      id: '/vault/$vaultId/thread/$threadId'
      path: '/thread/$threadId'
      fullPath: '/vault/$vaultId/thread/$threadId'
      preLoaderRoute: typeof VaultVaultIdThreadThreadIdRouteImport
      parentRoute: typeof VaultVaultIdRoute
    }
  }
}

interface VaultVaultIdRouteChildren {
  VaultVaultIdSettingsRoute: typeof VaultVaultIdSettingsRoute
  VaultVaultIdIndexRoute: typeof VaultVaultIdIndexRoute
  VaultVaultIdThreadThreadIdRoute: typeof VaultVaultIdThreadThreadIdRoute
}

const VaultVaultIdRouteChildren: VaultVaultIdRouteChildren = {
  VaultVaultIdSettingsRoute: VaultVaultIdSettingsRoute,
  VaultVaultIdIndexRoute: VaultVaultIdIndexRoute,
  VaultVaultIdThreadThreadIdRoute: VaultVaultIdThreadThreadIdRoute,
}

const VaultVaultIdRouteWithChildren = VaultVaultIdRoute._addFileChildren(
  VaultVaultIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  VaultVaultIdRoute: VaultVaultIdRouteWithChildren,
  WelcomeIndexRoute: WelcomeIndexRoute,
  ChatPopupThreadIdIndexRoute: ChatPopupThreadIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
