// Icon configuration that mirrors JetbrainsIconTheme format
// Each icon has dark and light variants

export const fileIcons = {
	// Default fallback
	default: 'text',

	// Icon definitions with dark/light variants
	icons: {
		// File icons
		text: { dark: 'text_dark', light: 'text' },
		markdown: { dark: 'markdown_dark', light: 'markdown' },
		json: { dark: 'json_dark', light: 'json' },
		yaml: { dark: 'yaml_dark', light: 'yaml' },
		lock: { dark: 'lock_dark', light: 'lock' },
		typescript: { dark: 'typeScript_dark', light: 'typeScript' },
		javascript: { dark: 'javaScript_dark', light: 'javaScript' },
		react: { dark: 'react_dark', light: 'react' },
		jsx: { dark: 'jsx_dark', light: 'jsx' },
		css: { dark: 'css', light: 'css' },
		scss: { dark: 'scss', light: 'scss' },
		html: { dark: 'html_dark', light: 'html' },
		image: { dark: 'image_dark', light: 'image' },
		python: { dark: 'python_dark', light: 'python' },
		go: { dark: 'go_dark', light: 'go' },
		goMod: { dark: 'goMod_dark', light: 'goMod' },
		goSum: { dark: 'goSum_dark', light: 'goSum' },
		goWork: { dark: 'goWork_dark', light: 'goWork' },
		goTest: { dark: 'goTest_dark', light: 'goTest' },
		goTemplate: { dark: 'goTemplate_dark', light: 'goTemplate' },
		goRunApplication: {
			dark: 'goRunApplication_dark',
			light: 'goRunApplication',
		},
		rust: { dark: 'rustFile_dark', light: 'rustFile' },
		java: { dark: 'java_dark', light: 'java' },
		kotlin: { dark: 'kotlin_dark', light: 'kotlin' },
		dart: { dark: 'dart_dark', light: 'dart' },
		cpp: { dark: 'cpp_dark', light: 'cpp' },
		c: { dark: 'c_dark', light: 'c' },
		cu: { dark: 'cu_dark', light: 'cu' },
		cuh: { dark: 'cuh_dark', light: 'cuh' },
		h: { dark: 'h_dark', light: 'h' },
		scala: { dark: 'scala_dark', light: 'scala' },
		swift: { dark: 'swift', light: 'swift' },
		ruby: { dark: 'ruby_dark', light: 'ruby' },
		rubyGems: { dark: 'rubyGems_dark', light: 'rubyGems' },
		rakeTask: { dark: 'rakeTask_dark', light: 'rakeTask' },
		elixir: { dark: 'elixir_dark', light: 'elixir' },
		eex: { dark: 'eex_dark', light: 'eex' },
		beam: { dark: 'beam', light: 'beam' },
		erlang: { dark: 'erlang', light: 'erlang' },
		clojure: { dark: 'clojure', light: 'clojure' },
		ml: { dark: 'ml', light: 'ml' },
		mli: { dark: 'mli', light: 'mli' },
		opam: { dark: 'opam', light: 'opam' },
		php: { dark: 'php_dark', light: 'php' },
		pythonTests: { dark: 'pythonTests_dark', light: 'pythonTests' },
		pythonConsole: { dark: 'pythonConsole_dark', light: 'pythonConsole' },
		docker: { dark: 'docker_dark', light: 'docker' },
		dockerfile: { dark: 'docker_dark', light: 'docker' },
		ignored: { dark: 'ignored_dark', light: 'ignored' },
		gitignore: { dark: 'gitignore', light: 'gitignore' },
		editorConfig: { dark: 'editorConfig_dark', light: 'editorConfig' },
		dune: { dark: 'dune', light: 'dune' },
		cargo: { dark: 'cargo_dark', light: 'cargo' },
		cargoLock: { dark: 'cargoLock_dark', light: 'cargoLock' },
		CMake: { dark: 'CMake_dark', light: 'CMake' },
		makefile: { dark: 'makefile_dark', light: 'makefile' },
		shell: { dark: 'shell_dark', light: 'shell' },
		sh: { dark: 'shell_dark', light: 'shell' },
		zsh: { dark: 'shell_dark', light: 'shell' },
		bash: { dark: 'shell_dark', light: 'shell' },
		bat: { dark: 'shell_dark', light: 'shell' },
		ps1: { dark: 'shell_dark', light: 'shell' },
		pnpm: { dark: 'pnpm_dark', light: 'pnpm' },
		yarn: { dark: 'yarn', light: 'yarn' },
		toml: { dark: 'toml_dark', light: 'toml' },
		xml: { dark: 'xml_dark', light: 'xml' },
		sql: { dark: 'sql_dark', light: 'sql' },
		dbms: { dark: 'dbms_dark', light: 'dbms' },
		archive: { dark: 'archive_dark', light: 'archive' },
		font: { dark: 'font_dark', light: 'font' },
		vueJs: { dark: 'vueJs', light: 'vueJs' },
		svelte: { dark: 'svelte', light: 'svelte' },
		slim: { dark: 'slim_dark', light: 'slim' },
		erbFile: { dark: 'erbFile_dark', light: 'erbFile' },
		less: { dark: 'less_dark', light: 'less' },
		csv: { dark: 'csv_dark', light: 'csv' },
		terraform: { dark: 'terraform_dark', light: 'terraform' },
		http: { dark: 'http_dark', light: 'http' },
		rest: { dark: 'http_dark', light: 'http' },
		actionScript: { dark: 'actionScript_dark', light: 'actionScript' },
		config: { dark: 'config_dark', light: 'config' },
		properties: { dark: 'properties_dark', light: 'properties' },
		application: { dark: 'application_dark', light: 'application' },
		protobuf: { dark: 'protoFile_dark', light: 'protoFile' },
		protoFile: { dark: 'protoFile_dark', light: 'protoFile' },
		hcl: { dark: 'hcl_dark', light: 'hcl_light' },
		rego: { dark: 'rego', light: 'rego' },
		solution: { dark: 'solution_dark', light: 'solution' },
		cs: { dark: 'cs_dark', light: 'cs' },
		cshtml: { dark: 'cshtml_dark', light: 'cshtml' },
		csproj: { dark: 'csproj_dark', light: 'csproj' },
		projectProperties: {
			dark: 'projectProperties_dark',
			light: 'projectProperties',
		},
		jupyter: { dark: 'jupyter', light: 'jupyter' },
		mdx: { dark: 'mdx', light: 'mdx' },
		lua: { dark: 'lua', light: 'lua' },
		haskell: { dark: 'haskell', light: 'haskell' },
		graphql: { dark: 'graphql', light: 'graphql' },
		gql: { dark: 'graphql', light: 'graphql' },
		eslint: { dark: 'eslint', light: 'eslint' },
		angularJS: { dark: 'angularJS', light: 'angularJS' },
		tailwind: { dark: 'tailwind', light: 'tailwind' },
		vite: { dark: 'vite_dark', light: 'vite' },
		postcss: { dark: 'postcss', light: 'postcss' },
		pdf: { dark: 'pdf', light: 'pdf' },
		jenkins: { dark: 'jenkins', light: 'jenkins' },
		groovy: { dark: 'groovy_dark', light: 'groovy' },
		schema: { dark: 'schema_dark', light: 'schema' },
		gleam: { dark: 'gleam_dark', light: 'gleam' },
		ino: { dark: 'ino_dark', light: 'ino' },
		tsTest: { dark: 'tsTest_dark', light: 'tsTest' },
		tsxTest: { dark: 'tsxTest_dark', light: 'tsxTest' },
		jsTest: { dark: 'jsTest_dark', light: 'jsTest' },
		jsxTest: { dark: 'jsxTest_dark', light: 'jsxTest' },
		jinja: { dark: 'jinja_dark', light: 'jinja' },
		jinja2: { dark: 'jinja_dark', light: 'jinja' },
		j2: { dark: 'jinja_dark', light: 'jinja' },
		'html.j2': { dark: 'jinja_dark', light: 'jinja' },
		gohtml: { dark: 'goTemplate_dark', light: 'goTemplate' },
		gotmpl: { dark: 'goTemplate_dark', light: 'goTemplate' },
	},

	// fileNames mapping: filename -> icon key
	fileNames: {
		dune: 'dune',
		'dune-project': 'dune',
		'.gitignore': 'gitignore',
		'.gitattributes': 'gitignore',
		'.gitmodules': 'gitignore',
		'.gitkeep': 'gitignore',
		'.editorconfig': 'editorConfig',
		'.yarnrc': 'yarn',
		'yarn.lock': 'yarn',
		README: 'markdown',
		'.dockerignore': 'ignored',
		Dockerfile: 'docker',
		'Dockerfile.dev': 'docker',
		'Dockerfile.test': 'docker',
		'Dockerfile.staging': 'docker',
		'Dockerfile.prod': 'docker',
		'Dockerfile.production': 'docker',
		Gemfile: 'rubyGems',
		'Gemfile.lock': 'rubyGems',
		Makefile: 'makefile',
		'.env': 'text',
		'.env.local': 'text',
		'.env.test': 'text',
		'.env.example': 'text',
		'.env.development': 'text',
		'.env.production': 'text',
		'.env.test.local': 'text',
		'.env.development.local': 'text',
		'.env.production.local': 'text',
		'.env.db': 'text',
		'Cargo.toml': 'cargo',
		'rust-toolchain.toml': 'cargo',
		'Cargo.lock': 'cargoLock',
		'CMakeLists.txt': 'CMake',
		'CMakeCache.txt': 'config',
		'pnpm-lock.yaml': 'pnpm',
		'pnpm-workspace.yaml': 'pnpm',
		'tailwind.config.js': 'tailwind',
		'tailwind.config.cjs': 'tailwind',
		'tailwind.config.ts': 'tailwind',
		'vite.config.js': 'vite',
		'vite.config.cjs': 'vite',
		'vite.config.ts': 'vite',
		'postcss.config.js': 'postcss',
		'postcss.config.cjs': 'postcss',
		'postcss.config.ts': 'postcss',
		'angular.json': 'angularJS',
		'.eslintrc': 'eslint',
		'.eslintrc.cjs': 'eslint',
		'.eslintrc.js': 'eslint',
		'.eslintrc.ts': 'eslint',
		'.eslintrc.json': 'eslint',
		'.eslintrc.yml': 'eslint',
		'.eslintrc.yaml': 'eslint',
		'.eslintignore': 'eslint',
		'go.mod': 'goMod',
		'go.sum': 'goSum',
		'go.work': 'goWork',
		'Directory.Build.props': 'projectProperties',
		'main.go': 'goRunApplication',
		'conftest.py': 'pythonTests',
		'__init__.py': 'pythonConsole',
		Jenkinsfile: 'jenkins',
	},

	// fileExtensions mapping: extension -> icon key
	fileExtensions: {
		// ML family
		ml: 'ml',
		mli: 'mli',
		opam: 'opam',
		// Styles
		css: 'css',
		scss: 'scss',
		sass: 'scss',
		less: 'less',
		// Kotlin
		kt: 'kotlin',
		// JSON
		json: 'json',
		jsonc: 'json',
		json5: 'json',
		arb: 'json',
		// HTML/JSX
		html: 'html',
		jsx: 'jsx',
		tsx: 'react',
		// JavaScript
		js: 'javascript',
		cjs: 'javascript',
		mjs: 'javascript',
		// TypeScript
		ts: 'typescript',
		cts: 'typescript',
		mts: 'typescript',
		// Ruby
		rake: 'rakeTask',
		rb: 'ruby',
		// Images
		png: 'image',
		webp: 'image',
		jpg: 'image',
		jpeg: 'image',
		gif: 'image',
		ico: 'image',
		svg: 'image',
		// Fonts
		ttf: 'font',
		woff: 'font',
		oft: 'font',
		eot: 'font',
		// Config
		yaml: 'yaml',
		yml: 'yaml',
		xml: 'xml',
		toml: 'toml',
		// Scala
		scala: 'scala',
		// Dart
		dart: 'dart',
		// Archives
		gz: 'archive',
		zip: 'archive',
		rar: 'archive',
		'7z': 'archive',
		tar: 'archive',
		// Python
		py: 'python',
		pyi: 'python',
		pyc: 'python',
		// Terraform
		tf: 'terraform',
		// Go
		go: 'go',
		http: 'http',
		rest: 'http',
		// PHP
		php: 'php',
		// Shell
		sh: 'shell',
		zsh: 'shell',
		bash: 'shell',
		bat: 'shell',
		ps1: 'shell',
		// C/C++
		h: 'h',
		hh: 'h',
		hpp: 'h',
		hxx: 'h',
		c: 'c',
		cc: 'cpp',
		cpp: 'cpp',
		cxx: 'cpp',
		ccm: 'cpp',
		cxxm: 'cpp',
		cppm: 'cpp',
		'c++m': 'cpp',
		ixx: 'cpp',
		cu: 'cu',
		cuh: 'cuh',
		// Rust
		rs: 'rust',
		// C#
		cs: 'cs',
		cshtml: 'cshtml',
		csproj: 'csproj',
		// Elixir/Erlang
		ex: 'elixir',
		exs: 'elixir',
		eex: 'eex',
		heex: 'eex',
		leex: 'eex',
		beam: 'beam',
		erl: 'erlang',
		// Swift
		swift: 'swift',
		// Vue
		vue: 'vueJs',
		// Svelte
		svelte: 'svelte',
		slim: 'slim',
		// Database
		sql: 'sql',
		db: 'dbms',
		sqlite: 'dbms',
		sqlite3: 'dbms',
		db3: 'dbms',
		accdb: 'dbms',
		mdb: 'dbms',
		dbf: 'dbms',
		ndf: 'dbms',
		ibd: 'dbms',
		frm: 'dbms',
		ora: 'dbms',
		// Lock
		lock: 'lock',
		// Markdown
		md: 'markdown',
		mdx: 'mdx',
		// Erlang
		cljc: 'clojure',
		cljs: 'clojure',
		clj: 'clojure',
		edn: 'clojure',
		// Config files
		cfg: 'config',
		conf: 'config',
		config: 'config',
		cnf: 'config',
		properties: 'properties',
		// Proto
		proto: 'protobuf',
		// HCL
		hcl: 'hcl',
		// Rego
		rego: 'rego',
		// Executable
		exe: 'application',
		// Jupyter
		ipynb: 'jupyter',
		// Shell
		ino: 'ino',
		// Templates
		jinja: 'jinja',
		jinja2: 'jinja',
		j2: 'jinja',
		'html.j2': 'jinja',
		gohtml: 'goTemplate',
		gotmpl: 'goTemplate',
		// CMake
		cmake: 'CMake',
		// Build
		sln: 'solution',
		// Dartino
		actionScript: 'actionScript',
		// Misc
		pdf: 'pdf',
		graphql: 'graphql',
		gql: 'graphql',
		lua: 'lua',
		haskell: 'haskell',
		jenkins: 'jenkins',
		groovy: 'groovy',
		bpmn: 'schema',
		// Tests
		'test.ts': 'tsTest',
		'test.tsx': 'tsxTest',
		'test.jsx': 'jsxTest',
		'test.js': 'jsTest',
		// SASS
		erb: 'erbFile',
	},
} as const

export type IconKey = keyof typeof fileIcons.icons
